### ISSUE TITLE
save error

### ISSUE THREAD

**Issue by Arthassssss** [liuhuanyong/SiameseSentenceSimilarity#3]
Traceback (most recent call last):
  File "siamese_model.py", line 242, in <module>
    handler.train_model()
  File "siamese_model.py", line 195, in train_model
    model.save(self.model_path)
  File "/root/anaconda3/lib/python3.6/site-packages/keras/engine/network.py", line 1090, in save
    save_model(self, filepath, overwrite, include_optimizer)
  File "/root/anaconda3/lib/python3.6/site-packages/keras/engine/saving.py", line 382, in save_model
    _serialize_model(model, f, include_optimizer)
  File "/root/anaconda3/lib/python3.6/site-packages/keras/engine/saving.py", line 84, in _serialize_model
    model_config = json.dumps(model_config, default=get_json_type)
  File "/root/anaconda3/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/root/anaconda3/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/root/anaconda3/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/root/anaconda3/lib/python3.6/site-packages/keras/engine/saving.py", line 74, in get_json_type
    raise TypeError('Not JSON Serializable: %s' % (obj,))
TypeError: Not JSON Serializable: <__main__.SiameseNetwork object at 0x7feec034c710>

**Comment by yuansky** [comment]
遇到了同样的问题，请问您解决了么

**Comment by David-webb** [comment]
@Arthassssss @yuansky @liuhuanyong 该问题是Lambda层的定义导致的，做如下修改，可正常训练和保存：
![siameses_1](https://user-images.githubusercontent.com/12361815/53612943-66e57300-3c0f-11e9-9c6b-70478394abc1.png)
![siameses_2](https://user-images.githubusercontent.com/12361815/53612952-6baa2700-3c0f-11e9-86b1-c99d218becd2.png)

**Comment by clancylee** [comment]
@David-webb 老哥你好，我把保存模型save_weights时候就不会报序列化错误，具体还在查！

**Comment by liuhuanyong** [comment]
@all, 已修复模型保存的错误。并更新至最新脚本，脚本最后可成功执行。

**Comment by Ellie24678** [comment]
@David-webb 您好，我想问下关于在使用load_model调用时，报错“‘NoneType’ object has no attribute 'get' ”。这个错误如果按你第二张图片进行修改的话，后面模型调用的时候需不需要另外加参数。比如：加上自定义的名称。
